const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const base=path.resolve(__dirname,'../dist');const replace=(id,exports)=>{require.cache[require.resolve(id)]={exports}};
let auditRows=new Map(),auditFail=false,calls=[],mode='good',draft='O titular pode pedir a eliminação dos dados tratados com consentimento.',judgeFail=false;
const source='O titular pode pedir a eliminação dos dados tratados com consentimento. A declaração completa de acesso deve ser fornecida em até 15 dias. O vazamento de dados sensíveis pode gerar dano moral presumido neste precedente.';
const chunk={id:'chunk-1',sourceId:'source-1',version:'source-version',content:source,score:0.8,chapter:'Direitos',areas:['lgpd'],fontes:['LGPD'],published:true};
replace(path.join(base,'config/env.js'),{env:{ANTHROPIC_API_KEY:'fake',JUDITH_MODEL_HAIKU:'judge-model'}});
replace(path.join(base,'db/client.js'),{prisma:{knowledgeInteraction:{create:async({data})=>{if(auditFail)throw Error('private-db-error');assert.ok(!auditRows.has(data.id));auditRows.set(data.id,data.payload)},update:async({where,data})=>{if(auditFail)throw Error('private-db-error');auditRows.set(where.id,data.payload)}}}});
replace(path.join(base,'judith/prompts/principal.js'),{getPrincipalSnapshot:async()=>({text:'EDITORIAL UNCHANGED',version:'editorial-v1'})});
replace(path.join(base,'judith/conhecimento.js'),{getKnowledgeContext:async q=>({area:'lgpd',searchText:q+' contexto mínimo',chunks:[chunk],text:source})});
replace('@anthropic-ai/sdk',class{messages={create:async req=>{calls.push(req);if(req.tools?.[0]?.name === "support_verdict"){if(judgeFail)throw Error('private-provider-error');return {id:'judge-id',model:'judge-model',content:mode==='malformed'?[]:[{type:'tool_use',name:'support_verdict',input:{units:[{index:0,supported:mode!=='reject',conversational:false,evidence:[{chunkId:'chunk-1',lineStart:0,lineEnd:0}]}]}}]}}return {id:'generation-id',model:'generation-model',content:[{type:'tool_use',name:'grounded_answer',input:{scopeAnalysis:'mock scope',unsupported:draft.startsWith('SEM_SUPORTE'),answer:draft}}],usage:{input_tokens:1,output_tokens:1}}}}});
const {validateSupport,verifySupport,SUPPORT_POLICY,conversationalOnly,materializeEvidence}=require('../dist/knowledge/support.js');
const {askJudith}=require('../dist/judith/claude.js');
const vote=(quote=source)=>({units:[{index:0,supported:true,conversational:false,evidence:[{chunkId:'chunk-1',quote}]}]});
test('known scope substitutions rejected even if reviewer incorrectly approves',()=>{
 assert.equal(conversationalOnly('Oi! Ótima pergunta.'),true);
 const raw={units:[{index:0,supported:true,conversational:false,evidence:[{chunkId:'chunk-1',lineStart:0,lineEnd:0}]}]};
 assert.equal(materializeEvidence(raw,[chunk]).units[0].evidence[0].quote,source);
 raw.units[0].evidence[0].lineEnd=100;
 assert.equal(validateSupport('Texto',[chunk],materializeEvidence(raw,[chunk])),false);
 assert.equal(conversationalOnly('Ficou claro? Posso te ajudar em mais alguma coisa?'),true);
 assert.equal(conversationalOnly('## A recusa gera dano presumido.'),false);
 for(const text of ['Você deve apagar os dados em 15 dias.','Basta a recusa de exclusão para gerar indenização presumida.','A maioria dos pequenos empresários perde.','A multa é de 90%.'])assert.equal(validateSupport(text,[chunk],vote()),false,text);
 assert.equal(validateSupport('O titular pode pedir a eliminação dos dados tratados com consentimento.',[chunk],vote()),true);
 assert.equal(validateSupport('O titular pode pedir a eliminação; a lei chama isso de direito ao esquecimento.',[chunk],vote()),false);
 assert.equal(validateSupport('A única exceção é a obrigação legal.',[chunk],vote()),false);
 const deadline='O prazo conta da assinatura do contrato ou do recebimento do produto.';
 const deadlineChunk={...chunk,content:deadline};
 assert.equal(validateSupport(deadline,[deadlineChunk],vote(deadline)),true);
 assert.equal(validateSupport(deadline+' O que for posterior.',[deadlineChunk],vote(deadline)),false);
 assert.equal(validateSupport(deadline+' O que vier depois.',[deadlineChunk],vote(deadline)),false);
 const explicit=deadline+' O que for posterior.';
 assert.equal(validateSupport(explicit,[{...chunk,content:explicit}],vote(explicit)),true);
 assert.equal(validateSupport('O comerciante responde pelo vício apenas em casos específicos.',[{...chunk,chapter:'RESPONSABILIDADE POR ACIDENTE DE CONSUMO'}],vote()),false);
 assert.equal(validateSupport('O comerciante responde apenas em casos específicos.',[{...chunk,chapter:'RESPONSABILIDADE POR ACIDENTE DE CONSUMO'}],vote(),'Quem responde pelo vício do produto?'),false);
 assert.equal(validateSupport('A declaração completa de acesso deve ser fornecida em até 15 dias.',[chunk],vote()),true);
 assert.equal(validateSupport('Pode apagar.',[chunk],vote('citação que não existe na fonte')),false);
 assert.equal(validateSupport('Texto',[chunk],{units:[{index:0,supported:true,conversational:true,evidence:[]}]}),false);
 assert.equal(validateSupport('Oi!\n\nPrazo 15 dias',[chunk],vote()),false);
 assert.equal(validateSupport('Oi!',[chunk],{units:[vote().units[0],vote().units[0]]}),false);
});
test('verificação usa somente escopos aplicáveis e registra exclusão; citação de bloco excluído não vira evidência',async()=>{
 const accident={...chunk,id:'accident',chapter:'ACIDENTE DE CONSUMO'};
 const result=await verifySupport('Quem responde pelo vício do produto?',[],draft,[chunk,accident]);
 assert.deepEqual(result.sourceIds,['chunk-1']);assert.deepEqual(result.excludedSourceIds,['accident']);
 assert.deepEqual(JSON.parse(calls.at(-1).messages[0].content).sources.map(c=>c.id),['chunk-1']);
 const raw={units:[{index:0,supported:true,conversational:false,evidence:[{chunkId:'accident',lineStart:0,lineEnd:0}]}]};
 assert.equal(validateSupport(draft,[chunk,accident],materializeEvidence(raw,[chunk])),false);
 calls=[];
});

test('two-question and continuation pipeline, trace privacy, fail closed',async()=>{
 let id=0;const run=(q,history=[])=>askJudith({tier:'HAIKU',funcao:'duvida',user:null,history,userMessage:q,interactionId:'interaction-'+(++id)});
 const q='Pela LGPD, um cliente pode pedir a eliminação de dados?';
 await run(q);const first=auditRows.get('interaction-1');
 assert.equal(JSON.parse(calls.at(-1).messages[0].content).sources[0].chapter,'Direitos');
 assert.equal(first.area,'lgpd');assert.equal(first.searchQuery,q+' contexto mínimo');assert.equal(first.chunks[0].id,'chunk-1');assert.equal(first.chunks[0].version,'source-version');assert.equal(first.chunks[0].content,source);assert.equal(first.prompt.version,'editorial-v1');assert.equal(first.actualModel,'generation-model');assert.equal(first.stage,'support_passed');
 assert.ok(!JSON.stringify(first).includes('EDITORIAL UNCHANGED'));assert.ok(!('user' in first));
 assert.equal(first.generationPolicy.version,'grounded-generation-v6');
 const generation=calls.find(c=>c.tools?.[0]?.name === "grounded_answer");assert.equal(generation.system[0].text,'EDITORIAL UNCHANGED');
 assert.ok(generation.system.some(b=>b.text.includes('SOMENTE à pergunta atual')));
 const beforeSentinel=calls.length;draft='SEM_SUPORTE';
 await assert.rejects(run('Qual a estatística ausente?'),e=>e.code==='SUPPORT_INSUFFICIENT');
 assert.equal(calls.length,beforeSentinel+1);assert.equal(auditRows.get('interaction-2').stage,'generation_no_support');
 const history=[{role:'user',content:q},{role:'assistant',content:'AFIRMAÇÃO ANTERIOR NÃO É FONTE'}];
 draft='Basta a recusa de exclusão para gerar indenização presumida.';
 await assert.rejects(run('E se a empresa se recusar a apagar?',history),e=>e.code==='SUPPORT_INSUFFICIENT');
 assert.equal(auditRows.get('interaction-3').stage,'support_rejected');
 assert.ok(!calls.at(-1).messages[0].content.includes('AFIRMAÇÃO ANTERIOR'));
 for(const q of ['E se forem dados financeiros?','Qual a chance de ganhar?','Agora quero acessar meus dados.']){
   mode='reject';draft='Consequência não sustentada pela fonte.';await assert.rejects(run(q,history),e=>e.code==='SUPPORT_INSUFFICIENT');
 }
 mode='malformed';await assert.rejects(run(q),e=>e.code==='SUPPORT_UNAVAILABLE');
 mode='good';draft='Ele pode revogar o consentimento e você tem até **15 dias** para apagar os dados.';
 await assert.rejects(run(q),e=>e.code==='SUPPORT_INSUFFICIENT');
 mode='good';judgeFail=true;await assert.rejects(run(q),e=>e.code==='SUPPORT_UNAVAILABLE');judgeFail=false;
 auditFail=true;const before=calls.length;await assert.rejects(run(q),e=>e.code==='TRACE_UNAVAILABLE');assert.equal(calls.length,before);auditFail=false;
 assert.match(SUPPORT_POLICY,/vazamento não implica recusa/);
 assert.match(SUPPORT_POLICY,/não garantia/);
});
